# Generated by Django 4.2.4 on 2023-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Module',
            fields=[
                ('mod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dbp_price', models.IntegerField()),
                ('dap', models.FloatField()),
                ('waiting_charge', models.FloatField()),
                ('waiting_time', models.FloatField()),
                ('status', models.TextField(max_length=200)),
                ('usermodifiedby', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
