# Generated by Django 4.2.4 on 2023-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_pricing_module_status_week_table_tmf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_module',
            name='dbp_km',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='dbp_price',
            field=models.FloatField(),
        ),
    ]
