# Generated by Django 4.2.4 on 2023-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_pricing_module_dbp_km_alter_pricing_module_dbp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_module',
            name='usermodifiedby',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='week_table',
            name='weekday',
            field=models.TextField(max_length=20),
        ),
    ]
