# Generated by Django 4.2.4 on 2023-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_pricing_module_usermodifiedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_module',
            name='usermodifiedby',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='week_table',
            name='weekday',
            field=models.CharField(max_length=20),
        ),
    ]
