# Generated by Django 4.2.4 on 2023-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_pricing_module_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
