# Generated by Django 4.2.4 on 2023-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_pricing_module_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_module',
            name='mod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
