# Generated by Django 4.2.4 on 2023-08-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_pricing_module_mod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_module',
            name='dbp_km',
            field=models.FloatField(default=True),
        ),
    ]
