# Generated by Django 4.2.4 on 2023-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_alter_pricing_module_dbp_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rides",
            fields=[
                ("ride_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_kms", models.FloatField(default=True)),
                ("total_time", models.FloatField(default=True)),
                ("total_charges", models.FloatField(default=True)),
                ("day", models.CharField(max_length=20)),
            ],
        ),
    ]
