# Generated by Django 4.2.4 on 2023-08-28 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_rides"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rides",
            old_name="ride_id",
            new_name="mod_id",
        ),
    ]
