# Generated by Django 4.2.4 on 2023-08-28 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_rename_ride_id_rides_mod_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rides",
            new_name="Ride",
        ),
    ]
