# Generated by Django 4.2.4 on 2023-08-28 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0012_rename_rides_ride"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
